build:
    image: kradalby/ci-node:latest
    pull: true
    commands:
      - apt update
      - apt upgrade -y
      - apt-get install ruby ruby-dev gcc make icnsutils graphicsmagick xz-utils gem gcc-multilib g++-multilib
      - npm set progress=false
      - npm install
      - npm install rcedit
      - npm run dist
      - ls -lah release/

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

deploy:
  rsync:
    user: www
    host: onyx.fap.no
    port: 22
    source: release/
    target: /storage/www/p0sX/
    delete: false
    recursive: true
    exclude:
        #    when:
        #        branch: master
    commands:
      - echo "Done"
