build:
    bundle:
        image: kradalby/ci-node-electron:latest
        pull: true
        commands:
          - apt update
          - apt upgrade -y
          - gem update fpm
          - npm set progress=false
          - npm install
          - npm install 7zip-bin-linux
          - npm run build
          # - npm run dist:darwin
          - npm run dist:win32
          - npm run dist:linux
        when:
            branch: master
    builder:
        image: kradalby/ci-node-electron:latest
        pull: true
        commands:
          - apt update
          - apt upgrade -y
          - npm set progress=false
          - npm install
          - npm run build
        when:
            branch: "!master"

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    when:
        branch: master
    recipients:
      - kradalby@kradalby.no

deploy:
  rsync:
    user: www
    host: onyx.fap.no
    port: 22
    source: dist/
    target: /storage/www/p0sX/
    delete: false
    recursive: true
    when:
        branch: master
    commands:
      - echo "Done"
