build:
    bundle:
        image: kradalby/ci-node-electron:latest
        pull: true
        commands:
          - apt-get update
          - apt-get install -y libudev-dev
          - gem update fpm
          - npm set progress=false
          - npm prune
          - npm install
          - npm install 7zip-bin-linux
          - cd app && npm install && cd ..
          - npm run lint
          - npm run build
          # - npm run dist:darwin
          - npm run dist:win32
          - npm run dist:linux
        when:
            branch: master
    builder:
        image: kradalby/ci-node-electron:latest
        pull: true
        commands:
          - npm set progress=false
          - npm install
          - npm run lint
          - npm run build
        when:
            branch: "!master"

cache:
    mount:
        - node_modules
notify:
    slack:
        webhook_url: https://hooks.slack.com/services/T03UG586F/$$SLACK_TOKEN_1/$$SLACK_TOKEN_2
        channel: teknisk-dev
        username: drone
        when:
            branch: master

deploy:
  rsync:
    user: www
    host: seel.fap.no
    port: 22
    source: dist/
    target: /usr/local/www/p0sx.kradalby.no/
    delete: true
    recursive: true
    when:
        branch: master
    commands:
      - echo "Done"
