build:
    bundle:
        image: kradalby/ci-node-electron:latest
        pull: true
        commands:
          - apt update
          - apt upgrade -y
          - gem update fpm
          - npm set progress=false
          - npm install
          - npm install 7zip-bin-linux
          - npm run lint
          - npm run build
          # - npm run dist:darwin
          - npm run dist:win32
          - npm run dist:linux
        when:
            branch: master
    builder:
        image: kradalby/ci-node-electron:latest
        pull: true
        commands:
          - apt update
          - apt upgrade -y
          - npm set progress=false
          - npm install
          - npm run lint
          - npm run build
        when:
            branch: "!master"

cache:
    mount:
        - node_modules
notify:
    slack:
        webhook_url: https://hooks.slack.com/services/T03UG586F/$$SLACK_TOKEN_1/$$SLACK_TOKEN_2
        channel: teknisk-dev
        username: drone
        when:
            branch: master

deploy:
  rsync:
    user: www
    host: onyx.fap.no
    port: 22
    source: dist/
    target: /storage/www/p0sX/
    delete: false
    recursive: true
    when:
        branch: master
    commands:
      - echo "Done"
