
pipeline:
    pack:
        image: node:latest
        pull: true
        commands:
            - npm install -q
            - npm run lint -q
            - npm run dist:linux64
        when:
            event: [push, pull_request, deployment]

    pack:
        image: node:latest
        pull: true
        commands:
            - npm install -q
            - npm run lint -q
            - npm run dist:linux64
        when:
            event: tag

    notify:
        image: plugins/slack
        channel: teknisk-dev
        username: drone
        event: [push, pull_request, deployment, tag]
