
pipeline:
    pack:
        image: node:latest
        pull: true
        commands:
            - npm install -q -g electron-forge
            - npm install -q -g electron-builder
            - npm install -q
            - npm run lint -q
            - electron-forge package
        when:
            event: [push, pull_request, deployment]

    notify:
        image: plugins/slack
        channel: teknisk-dev
        username: drone
        event: [push, pull_request, deployment, tag]
